apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME-frontend
  namespace: $NAMESPACE
  labels:
    app: $APP_NAME-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: $APP_NAME-frontend
    spec:
      containers:
        - name: $APP_NAME-frontend
          image: $IMAGE-frontend:$VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
