apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-frontend
  namespace: $NAMESPACE
  labels:
    app: $APP_NAME-frontend
spec:
  type: ClusterIP
  selector:
    app: $APP_NAME-frontend
  ports:
    - name: http
      port: 80
