global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "iban_validation_api"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets:
          - $APP_NAME-api.$NAMESPACE.svc.cluster.local:8080
