apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME-api
  namespace: $NAMESPACE
  labels:
    app: $APP_NAME-api
spec:
  type: ClusterIP
  selector:
    app: $APP_NAME-api
  ports:
    - name: http
      port: 8080
