apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $APP_NAME-prometheus
  namespace: $NAMESPACE
  labels:
    app: $APP_NAME-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
