apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - ingress.yml

secretGenerator:
  - name: $APP_NAME-api
    literals:
      - IBAN_API_KEY=$IBAN_API_KEY
