apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml
  - prometheus/deployment.yml
  - prometheus/service.yml
  #- prometheus/ingress.yml
  - prometheus/persistentVolumeClaim.yml
  - grafana/deployment.yml
  - grafana/service.yml
  # - grafana/ingress.yml
  - grafana/persistentVolumeClaim.yml
  - ingress.yml

secretGenerator:
  - name: $APP_NAME-api
    namespace: $NAMESPACE
    env: .env
  - name: $APP_NAME-api-properties
    namespace: $NAMESPACE
    files:
      - application-live.properties
  - name: $APP_NAME-prometheus-auth
    namespace: $NAMESPACE
    files:
      - prometheus/config/auth

configMapGenerator:
  - name: $APP_NAME-prometheus-config
    namespace: $NAMESPACE
    files:
      - prometheus/config/prometheus.yml
  - name: $APP_NAME-grafana-config
    namespace: $NAMESPACE
    files:
      - grafana/config/grafana.ini

generatorOptions:
  disableNameSuffixHash: true
