global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "iban_validation_api"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["127.0.0.1:8080"]
